version: "3.3"
services:
  solr-8-1-1-ssl:
    image: solr:8.1.1
    restart: always
    ports:
      - 8983:8983
    environment:
      - SOLR_SSL_KEY_STORE=/opt/solr/server/certs/solr-ssl.keystore.pfx
      - SOLR_SSL_TRUST_STORE=/opt/solr/server/certs/solr-ssl.keystore.pfx
      - SOLR_SSL_KEY_STORE_PASSWORD=123SecureSolr!
      - SOLR_SSL_TRUST_STORE_PASSWORD=123SecureSolr!
    volumes:
      - ./certs:/opt/solr/server/certs
      - ./solr_home:/opt/solr/server/solr
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    tty: true  